### PR TITLE
Add primary unit tracking

### PR DESCRIPTION
**Pull request by hickorysb**
There are still a few more things to be added, such as a command to set yourself as the primary unit on your current call.

### CODE REVIEW

**Comment by AprilCatStreams** [comment]
### To-Do

- [x] Track Unit not postal (my bad)
- [ ] Add primary unit command
- [ ] Add command to toggle primary unit tracking (Only available to primary unit)
- [x] Add command to toggle primary unit tracking for other units

**Comment by nathanctech** [comment]
I can't modify the code myself, but I've  modified the code based on some testing today. See the pull-6 branch.

**Comment by AprilCatStreams** [comment]
#4251

**Comment by SonoranBrian** [comment]
Dev bounty has been sent, thank you for your submission.

**Pull request closed without merging**
